version: '2.0'

services:

  wordpress:
    build: .
    ports:
      - 30100:80
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: flag{6omDaHt4beJ2z1jRdJSz}
      WORDPRESS_DB_USER: wordpress
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dX2f3ul45OQ90S4TBBm8U7o5ozjTLlP9iyepezU0
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: flag{6omDaHt4beJ2z1jRdJSz}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
