version: "2"
services:
    redis:
        image: "redis"
        ports:
            - "6379"
        links:
            - uwsgi
        volumes:
            - ./data:/data
        command: redis-server --appendonly yes
        restart: always
    uwsgi:
        build:
            context: .
            dockerfile: ./docker/uwsgi/Dockerfile
        ports:
            - "30200:8000"
        volumes:
            - ./src:/code
        restart: always

